name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - scripts/Dockerfile.base
      - scripts/Dockerfile
  pull_request:
    paths:
      - scripts/Dockerfile.base
      - .github/workflows/docker-image.yml
      
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the docker image
      run: ./script/build_docker.sh
      
